### ISSUE TITLE
Output overlaps in default_2

### ISSUE THREAD

**Issue by Zepeng-Mu** [surbut/gtexresults_matrixash#3]
Hi I am running `sos dryrun workflows/fastqtl_to_mash.ipynb` and got the error `ERROR: [default_2]: Failed to process step output (f'{cwd:a}/{data_list:bn}.h5'): Output /path/to/gtexresults/fastqtl_to_mash_output/FastQTLSumStats.h5 from substep 1 overlaps with output from a previous substep
[default]: 2 pending steps: default_3, default_4`. I am not farmilar with sos at all and did not change the code I downloaded from the repo.

Thanks!

**Comment by gaow** [comment]
@Zepeng-Mu Just letting you know that the docker image has also been updated to reflect the change I pushed https://github.com/stephenslab/gtexresults/commit/4ba2f02211546c779bacb128a0b82a34ac0e96a4

Possibly relevant to your application: @zouyuxin and I have updated the `mashr_flashr_workflow.ipynb` pipeline with a new approach to estimate the residual covariance that should work better than previous approach when your samples from different conditions have overlaps. Please use `git pull` to get the updated pipeline, and take a look at available options using the `-h` command as documented in Cell 1 of the notebook. Specifically there is now a `--vhat` option:

1. `--vhat simple` (default)
2. `--vhat identity`
3. `--vhat mle`

To use @zouyuxin 's method, please add parameter `--vhat mle` to your command. You are also encouraged to use other options and compare results. We'd appreciate your feedback on this feature for your data!

**Comment by Zepeng-Mu** [comment]
Hi, I am running the workflow and got an error in `mash_1` saying that 
```
Error in (-npoint):0 : result would be too long a vector
Calls: saveRDS -> mash -> autoselect_grid
Execution halted
```.
Tracing back to the code, I found that while running 
```
mash(mash_data, Ulist = readRDS('/path/gtexresults/mashr_flashr_workflow_output/FastQTLSumStats.mash.EZ.FLError in (-npoint):0 : result would be too long a vectorithm.version = "Rcpp")
```
inside mash function my `gmin = 0`, which means that my `min(Shat)` is 0, which then cause `autoselect_grid()` to fail. Does this suggests that there was a problem in my data processing in previous steps?

Thank you so much!

**Comment by gaow** [comment]
@Zepeng-Mu indeed, I was able to reproduce it via:

```
> data = mashr::simple_sims()
> data$Shat[1,1] = 0
> mdata = mashr::mash_set_data(data$Bhat,Shat=data$Shat)
> grid = mashr:::autoselect_grid(mdata,sqrt(2))
Error in (-npoint):0 : result would be too long a vector
```

When we initiate the data object we [set missing Shat or infinity Shat to zero](https://github.com/stephenslab/mashr/blob/master/R/set_data.R#L59). Since your data preprocessing uses our pipeline we should not have picked any missing values for this set. Could you look into your data and check what caused Shat set to zero and report back here? Possibly infinity?

**Comment by gaow** [comment]
The fix is straightforward on our end:

```diff
diff --git a/R/mash.R b/R/mash.R
index 068cdb0..7eb9b8b 100644
--- a/R/mash.R
+++ b/R/mash.R
@@ -333,8 +333,9 @@ grid_max = function(Bhat,Shat){
 
 # Automatically select grid.
 autoselect_grid = function(data,mult){
-  gmax = grid_max(data$Bhat, data$Shat)
-  gmin = grid_min(data$Bhat, data$Shat)
+  include = !(data$Shat==0 | data$Shat == Inf | is.na(data$Bhat) | is.na(data$Shat))
+  gmax = grid_max(data$Bhat[include], data$Shat[include])
+  gmin = grid_min(data$Bhat[include], data$Shat[include])
   if (mult == 0) {
     return(c(0, gmax/2))
   }
```

but it is more worrisome that your data (or our preprocessing pipeline) has issues

**Comment by gaow** [comment]
@Zepeng-Mu see #4 for some details. If you update the data conversion pipeline and rerun the fastqtl to mash step you should not have a problem. In the future would you please open separate tickets for new issues? Thanks!

**Comment by pcarbo** [comment]
@gaow You should not use `x == Inf`, you should use `is.finite`, which also checks for `NaN`.

**Comment by gaow** [comment]
Thanks @pcarbo yes that was also what I did in #4 in Python. I now changed the R code to : 

```diff
 autoselect_grid = function(data,mult){
-  include = !(data$Shat==0 | data$Shat == Inf | is.na(data$Bhat) | is.na(data$Shat))
+  include = !(data$Shat==0 | !is.finite(data$Shat) | is.na(data$Bhat))
   gmax = grid_max(data$Bhat[include], data$Shat[include])
   gmin = grid_min(data$Bhat[include], data$Shat[include])
```

**Comment by gaow** [comment]
> data$Shat == 0 when the entry is NA will return NA, 

This is annoying ... 

> And normally the best solution is to not allow them, or remove them before doing anything else.

In fact this is the case for `mash_set_data` where we've handled the other cases. At this point Shat should already be replaced by zeros if it is `NA` so that line of code should be fine.
